server:
  port: 80
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbuser?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hn123456Aa
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.hunau
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
